# Generated by Django 4.2.1 on 2023-05-19 17:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Россия", max_length=50, verbose_name="страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="город"
                    ),
                ),
                ("street", models.CharField(max_length=50, verbose_name="улица")),
                (
                    "house",
                    models.SmallIntegerField(default=0, verbose_name="номер дома"),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название завода"),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="esalenet.contact",
                        verbose_name="Контакты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Завод",
                "verbose_name_plural": "Заводы",
            },
        ),
        migrations.CreateModel(
            name="LevelOneProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название завода"),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="esalenet.contact",
                        verbose_name="Контакты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик первого уровня",
                "verbose_name_plural": "Поставщики первого уровня",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Наименование товара"
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=100, verbose_name="модель товара"),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="дата выхода"
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="LevelTwoProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название завода"),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="esalenet.contact",
                        verbose_name="Контакты",
                    ),
                ),
                ("product", models.ManyToManyField(to="esalenet.product")),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="levelone",
                        to="esalenet.leveloneprovider",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик второго уровня",
                "verbose_name_plural": "Поставщики второго уровня",
            },
        ),
        migrations.AddField(
            model_name="leveloneprovider",
            name="product",
            field=models.ManyToManyField(to="esalenet.product"),
        ),
        migrations.AddField(
            model_name="leveloneprovider",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factory",
                to="esalenet.factory",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="factory",
            name="product",
            field=models.ManyToManyField(to="esalenet.product"),
        ),
    ]
