# Generated by Django 4.2.1 on 2023-05-21 14:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("esalenet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="factory",
            name="product",
            field=models.ManyToManyField(to="esalenet.product", verbose_name="Товары"),
        ),
        migrations.AlterField(
            model_name="leveloneprovider",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Задолженность поставщику",
            ),
        ),
        migrations.AlterField(
            model_name="leveloneprovider",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="leveloneprovider",
            name="product",
            field=models.ManyToManyField(to="esalenet.product", verbose_name="Товары"),
        ),
        migrations.AlterField(
            model_name="leveltwoprovider",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Задолженность поставщику",
            ),
        ),
        migrations.AlterField(
            model_name="leveltwoprovider",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="leveltwoprovider",
            name="product",
            field=models.ManyToManyField(to="esalenet.product", verbose_name="Товары"),
        ),
        migrations.AlterField(
            model_name="leveltwoprovider",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="levelone",
                to="esalenet.leveloneprovider",
                verbose_name="Поставщик",
            ),
        ),
    ]
