# Generated by Django 4.2.1 on 2023-05-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esalenet", "0002_alter_factory_name_alter_factory_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email address"),
        ),
    ]
