# Generated by Django 4.2.1 on 2023-05-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esalenet", "0003_alter_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True,
                default=None,
                max_length=254,
                null=True,
                verbose_name="email address",
            ),
        ),
    ]
